# Test your FastAPI endpoints


POST http://localhost:8000/sensor/hex
Content-Type: application/json

{
  "data": "34ffffff80490000804a0000804b0000804c0000804d000079f3ffff"
}


###

POST http://localhost:8000/sensor/file/hex
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="element-name"
Content-Type: text/plain

file
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test"
Content-Type: text/plain

< ./test
--WebAppBoundary--